import api from './request'

export const getDevices = params => api.get('/assets/device', { params })
export const createDevice = data => api.post('/assets/device', data)
export const getDevice = id => api.get(`/assets/device/${id}`)
export const updateDevice = (id, data) => api.put(`/assets/device/${id}`, data)
export const deleteDevice = id => api.delete(`/assets/device/${id}`)
export const setDeviceMaintain = id => api.post(`/assets/device/${id}/maintain`)
export const decommissionDevice = id => api.post(`/assets/device/${id}/decommission`)
export const getDeviceGroups = () => api.get('/assets/group')
export const getGroupDevices = id => api.get(`/assets/group/${id}/devices`)
export const getConfigItems = params => api.get('/assets/config', { params })
export const createConfigSnapshot = data => api.post('/assets/config/snapshot', data)
export const updateConfigItem = (id, data) => api.put(`/assets/config/${id}`, data)
export const deleteConfigItem = id => api.delete(`/assets/config/${id}`)
export const syncDeviceConfig = id => api.post(`/assets/config/sync/${id}`)
export const getBusinessSystems = params => api.get('/assets/business', { params })
export const getBusinessSystem = id => api.get(`/assets/business/${id}`)
export const getBusinessDevices = id => api.get(`/assets/business/${id}/devices`)
export const getAssetStats = () => api.get('/assets/stats')
